# Generated by Django 5.2 on 2026-02-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_time', models.FloatField(help_text='Time spent in minutes')),
                ('pages_visited', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('last_login_gap', models.IntegerField(help_text='Days since last login')),
                ('engagement_score', models.FloatField(blank=True, null=True)),
                ('churn_probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
